services:

  c2_server:
    image: kalilinux/kali-rolling
    container_name: c2_server
    networks:
      - cyberlab_net
    ports:
      - "4444:4444"
    tty: true
    stdin_open: true
    restart: unless-stopped

  victim:
    image: vulnerables/web-dvwa
    container_name: victim
    networks:
      - cyberlab_net
    ports:
      - "8080:80"
    restart: unless-stopped

  suricata:
    image: jasonish/suricata
    container_name: suricata
    networks:
      - cyberlab_net
    cap_add:
      - NET_ADMIN
      - SYS_NICE
    volumes:
      - ./suricata/config:/etc/suricata
      - ./suricata/log:/var/log/suricata
    command: ["-i", "eth0"]
    restart: unless-stopped

  splunk:
    image: splunk/splunk:latest
    container_name: splunk
    environment:
      - SPLUNK_START_ARGS=--accept-license
      - SPLUNK_PASSWORD=123!@#Fusing
    ports:
      - "8000:8000"
      - "8088:8088"
      - "9997:9997"
    networks:
      - cyberlab_net
    restart: unless-stopped

networks:
  cyberlab_net:
    external: true
